frontend:
  - changed-files:
      - any-glob-to-any-file: "frontend/**/*"
eslint:
  - changed-files:
      - any-glob-to-any-file: "packages/eslint-config-animeflix/**/*"
tsconfig:
  - changed-files:
      - any-glob-to-any-file: "packages/tsconfig/**/*"
api:
  - changed-files:
      - any-glob-to-any-file: "packages/api/**/*"
