param(
  [Parameter(Mandatory = $true)]
  [string]$NgrokDomain,

  [switch]$NoStart
)

$ErrorActionPreference = 'Stop'

$domain = $NgrokDomain.Trim()
$domain = $domain -replace '^https?://', ''
$domain = $domain.TrimEnd('/')

if ($domain -notmatch '^[a-zA-Z0-9.-]+\.ngrok-free\.(app|dev)$') {
  throw "Invalid ngrok free domain: $domain"
}

$toolDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$supervisor = Join-Path $toolDir 'relay-supervisor.mjs'
$log = Join-Path $toolDir 'relay.log'
$node = (Get-Command node -ErrorAction Stop).Source
$startup = [Environment]::GetFolderPath('Startup')
$launcher = Join-Path $startup 'kessoku-relay.vbs'

if (-not (Test-Path -LiteralPath $supervisor)) {
  throw "Relay supervisor not found: $supervisor"
}

function Escape-VbsString([string]$Value) {
  return $Value.Replace('"', '""')
}

$command = 'cmd /d /c set "NGROK_DOMAIN={0}" && "{1}" "{2}" >> "{3}" 2>&1' -f `
  $domain, $node, $supervisor, $log

$vbs = @"
' Kessoku Moe manhwatop relay. Generated by install-windows-autostart.ps1.
Set sh = CreateObject("Wscript.Shell")
sh.Run "$(Escape-VbsString $command)", 0, False
"@

Set-Content -LiteralPath $launcher -Value $vbs -Encoding ASCII

Write-Host "Installed hidden login launcher:"
Write-Host "  $launcher"
Write-Host "Domain:"
Write-Host "  https://$domain"

if (-not $NoStart) {
  $running = Get-CimInstance Win32_Process | Where-Object {
    $_.CommandLine -and
    $_.CommandLine.Contains($toolDir) -and
    $_.CommandLine -like '*relay*.mjs*'
  }

  if ($running) {
    Write-Host 'A relay process is already running; left it untouched.'
  } else {
    Start-Process -FilePath 'wscript.exe' -ArgumentList "`"$launcher`"" -WindowStyle Hidden
    Write-Host 'Relay supervisor started in the background.'
  }
}
